name: my_http
description: "A new Flutter project."
publish_to: 'none' # 🔒 يمنع نشر هذه الحزمة بالخطأ على موقع pub.dev (مخصص للمشاريع الخاصة)

version: 1.0.0+1 # 📌 رقم إصدار التطبيق (رقم الإصدار + رقم البناء الداخلي)

environment:
  sdk: ^3.11.5 # ⚙️ إصدار لغة Dart المطلوب لكي يعمل المشروع بشكل سليم

dependencies: # 📦 الحزم الأساسية التي ستبقى مدمجة مع التطبيق حتى بعد رفعه للمتاجر
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8 # 🍏 حزمة توفر أيقونات خاصة بأنظمة أبل (iOS)
  dio: ^5.11.0 # 🌐 مكتبة الاتصال القوية والمتقدمة لإرسال طلبات الـ GET والـ POST
  http: ^1.6.0 # 🔌 مكتبة فلاتر التقليدية لطلبات الشبكة (كخيار إضافي)
  json_annotation: ^4.12.0 # 🏷️ حزمة توفر الوسوم مثل @JsonSerializable() لربط البيانات

dev_dependencies: # 🛠️ حزم التطوير: تُستخدم على جهازك أثناء البرمجة فقط ولا يتم تضمينها في التطبيق النهائي
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0 # 🧹 مجموعة قواعد فحص ونظافة الكود لتجنب الأخطاء البرمجية
  
  # ⚙️ الأداة الثنائية لتوليد ملفات الـ g.dart تلقائياً:
  build_runner: ^2.4.8 # 👷 "المهندس الآلي" الذي ينفذ عملية التوليد في التيرمينال
  json_serializable: ^6.7.1 # 📝 الحزمة التي تنشئ دوال الـ fromJson و toJson نيابةً عنك

flutter:
  uses-material-design: true # 🎨 تفعيل استخدام خطوط وأيقونات Google Material Design الشهيرة